CREATE TABLE IF NOT EXISTS seasonings (
	id						BIGINT NOT NULL AUTO_INCREMENT,
	name					VARCHAR(100) NOT NULL,
	description				VARCHAR(100) NOT NULL,
	price					DECIMAL(8,2) NOT NULL,
	CONSTRAINT pk_seasonings_id PRIMARY KEY (id)
);